### ISSUE TITLE
Attributes need writing for computed variables

### ISSUE THREAD

**Issue by DavidMcCann-NOC** [ACHMartin/seastar_project#170]
Currently attributes e.g., 'long_name', 'units' are not present for computed data arrays. Need to add attributes at the end of computation functions.

**Comment by ACHMartin** [comment]
Priority for the Level2 data fields than the intermediate L1 products

**Comment by DavidMcCann-NOC** [comment]
Closed with commit #188

**Comment by DavidMcCann-NOC** [comment]
Long name should be just 'Current Velocity' rather than the current long names. Units without parentheses.

Revisit all dataarrays 

Look in to differences between 'long_name', 'standard_name' etc and their impact on plotting.

**Comment by DavidMcCann-NOC** [comment]
Perhaps a new attribute field with the description in it?

**Comment by DavidMcCann-NOC** [comment]
Attributes to be standardized in the following format:

- ``[long_name]`` = Short title for plotting purposes, e.g., ``'Radial surface current'``
- ``[description]`` = Long title, e.g., ``'Radial Surface Current (RSC) along antenna beam direction, corrected for Wind Artifact Surface Velocity (WASV)'``
- ``[units]`` = units in SI format as a ``str``, without brackets. e.g., ``'m/s'``
